language: shell

os: osx 

env: HOMEBREW_NO_EMOJI=1

jobs:
  include:
    - name: "macOS 10.14 Xcode 11"
      osx_image: xcode11
    - name: "macOS 10.14.4 Xcode 10.3"
      osx_image: xcode10.3
    - name: "macOS 10.14 Xcode 10.2.1"     
      osx_image: xcode10.2 
    - name: "macOS 10.13 Xcode 10.1" 
      osx_image: xcode10.1
#    - name: "macOS 10.13 Xcode 10.0"  
#      osx_image: xcode10
#    - name: "macOS 10.13 Xcode 9.4.1"   
#      osx_image: xcode9.4     


before_script:
  - brew update #>/dev/null

script:
  - brew tap orome/crypto-enigma
  - brew tap
  - brew install crypto-enigma
  - brew info crypto-enigma
  - which -a enigma
  - brew test crypto-enigma
  - enigma --version
  - enigma run "B-I-III-I EMO UX.MO.AY 13.04.11" -m "TESTING" -s 20
  - enigma run "B-I-III-I EMO UX.MO.AY 13.04.11" -m "SOFORT" -f config
  - enigma run "B-I-III-I EMO UX.MO.AY 13.04.11" -m "SOFORT" -f internal  

#addons:
#  ssh_known_hosts:
#  - github.com
